// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbSPMVLPkfaZG2AjfY1XXTtQ6bWJQ3FM',
    appId: '1:247737180304:web:aa959b9f37b5ae681e7815',
    messagingSenderId: '247737180304',
    projectId: 'easy-academia',
    authDomain: 'easy-academia.firebaseapp.com',
    storageBucket: 'easy-academia.firebasestorage.app',
    measurementId: 'G-JCENYBVSHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhzJgf9HX2ultrVFKF7x7oBf5tdi95LJs',
    appId: '1:247737180304:android:282baf51c37289681e7815',
    messagingSenderId: '247737180304',
    projectId: 'easy-academia',
    storageBucket: 'easy-academia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWsZhNDprgOisWRxYtZNWyKCHW8FPO2Sc',
    appId: '1:247737180304:ios:88f830aa20f9b4f71e7815',
    messagingSenderId: '247737180304',
    projectId: 'easy-academia',
    storageBucket: 'easy-academia.firebasestorage.app',
    iosBundleId: 'com.example.easyAcademia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWsZhNDprgOisWRxYtZNWyKCHW8FPO2Sc',
    appId: '1:247737180304:ios:88f830aa20f9b4f71e7815',
    messagingSenderId: '247737180304',
    projectId: 'easy-academia',
    storageBucket: 'easy-academia.firebasestorage.app',
    iosBundleId: 'com.example.easyAcademia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbSPMVLPkfaZG2AjfY1XXTtQ6bWJQ3FM',
    appId: '1:247737180304:web:b6c626928bf4aa201e7815',
    messagingSenderId: '247737180304',
    projectId: 'easy-academia',
    authDomain: 'easy-academia.firebaseapp.com',
    storageBucket: 'easy-academia.firebasestorage.app',
    measurementId: 'G-01WC6BXLEK',
  );
}
